# Generated by Django 3.2.8 on 2021-10-11 03:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=10)),
                ('sms_notification_active', models.BooleanField(default=False)),
                ('email_notification_active', models.BooleanField(default=False)),
                ('user_image', models.ImageField(blank=True, upload_to='')),
                ('registration', models.DateTimeField(default=datetime.datetime(2021, 10, 11, 3, 15, 30, 569592, tzinfo=utc))),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_post.usertype')),
            ],
        ),
    ]
