# Generated by Django 3.2.8 on 2021-10-11 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_useraccount_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
