# Generated by Django 3.2.8 on 2021-10-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.OneToOneField(default='static/images/default_pfp.png', on_delete=django.db.models.deletion.SET_DEFAULT, to='job_post.userimage'),
        ),
    ]
