# Generated by Django 3.2.8 on 2021-10-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0006_auto_20211026_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
