# Generated by Django 3.2.8 on 2021-10-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0007_alter_userimage_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_post.userimage'),
        ),
    ]
