# Generated by Django 3.2.8 on 2021-10-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
